# sonar-project.properties - CICD-2
# Va en: Alojamientos/sonar-project.properties

sonar.projectKey=alojamientos-hosped-backend
sonar.projectName=AlojamientosHosped - Backend

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.sourceEncoding=UTF-8
sonar.java.source=21

# Reporte de cobertura generado por JaCoCo
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

# CICD-2: El pipeline espera el resultado del Quality Gate antes de continuar
sonar.qualitygate.wait=true
# configuracion lista
# trigger pipeline